---@type LangFile
return {
    misc = {
        text_frame = "Frame",
        text_frame_plural = "Frames",
        text_disabled = "Disabled",
        text_master_rank_short = "M",
        text_village_short = "V",
        text_high_rank_short = "H",
        text_low_rank_short = "L",
        text_mystery_short = "A",
        text_random_mystery_short = "RA",
        text_rampage_short = "R",
        text_random_rampage_short = "RR",
        text_star = "★",
        text_none = "None",
        text_changed_notifcation_message = "changed to",
        text_any = "Any",
        text_special = "EX",
        text_or_higher = "or higher",
        text_or_lower = "or lower",
        text_favourite = "Favourite",
    },
    menu = {
        config = {
            name = "Mod",
            enable_key_binds = "Enable Key Binds",
            enable_notification = "Enable Notifications",
            hide_disabled = "Hide Disabled",
            tooltip_hide_disabled = "Hide some disabled gui elements.",
        },
        language = {
            name = "Language",
            fallback = "Fallback",
            fallback_tooltip = "Display message in english if key is missing",
        },
        bind = {
            name = "Bind",
            tooltip_bound = "Already bound to",
            slider_buffer = "Buffer",
            tooltip_buffer = "Time window to detect multi-key combination (e.g. A+B) before triggering single keys",
            text_default = "Press any key...",
            button_add = "Add",
            button_save = "Save",
            button_remove = "Remove",
            button_cancel = "Cancel",
            button_clear = "Clear",
        },
        randomizer = {
            name = "Randomizer",
            category_quest_rank = "Quest Rank",
            category_quest_type = "Quest Type",
            category_quest_category = "Quest Category",
            category_quest_level = "Quest Level",
            category_other = "Other",
            category_exclude_master_rank_level = "Exclude Master Rank Level",
            category_exclude_mystery_level = "Exclude Anomaly Level",
            category_exclude_random_mystery_level = "Exclude Random Mystery Level",
            box_exclude_village = "Exclude Village",
            box_exclude_low_rank = "Exclude Low Rank",
            box_exclude_high_rank = "Exclude High Rank",
            box_exclude_master_rank = "Exclude Master Rank",
            box_exclude_mystery = "Exclude Anomaly",
            box_exclude_special_random_mystery = "Exclude Special Random Anomaly",
            box_exclude_random_mystery = "Exclude Random Anomaly",
            slider_exclude_random_mystery_below = "Exclude Below",
            slider_exclude_random_mystery_above = "Exclude Above",
            box_exclude_normal = "Exclude Normal",
            box_exclude_rampage = "Exclude Rampage",
            box_exclude_random_rampage = "Exclude Random Rampage",
            box_exclude_arena = "Exclude Arena",
            box_exclude_servant_request = "Exclude Follower Request",
            box_exclude_kingdom = "Exclude Follower Quest",
            box_exclude_event = "Exclude Event",
            box_exclude_training = "Exclude Training",
            box_exclude_tour = "Exclude Tour",
            box_exclude_capture = "Exclude Capture",
            box_exclude_slay = "Exclude Slay",
            box_exclude_hunt = "Exclude Hunt",
            box_exclude_boss_rush = "Exclude Rush",
            box_exclude_gathering = "Exclude Gathering",
            box_exclude_zako = "Exclude Small Monster",
            box_exclude_one = "Exclude One Monster",
            box_exclude_multi = "Exclude Multi Monster",
            box_exclude_lock = "Exclude Not Unlocked",
            box_exclude_complete = "Exclude Completed",
            box_exclude_invalid_random_mystery = "Exclude Invalid Random Anomaly",
            box_exclude_custom = "Exclude Custom",
            box_exclude_no_custom = "Exclude Non Custom",
            box_exclude_post = "Exclude Posted",
            box_prefer_research_target = "Prefer Research Target",
            box_exclude_non_online = "Exclude Non Online",
            button_reset = "Reset Settings",
            button_reset_post = "Reset Posted",
            text_post_quest = "Posted Quests: ",
            text_quests = "Quests: ",
            item_settings = "Settings",
            tooltip_exclude_master_rank = "Does not exclude Anomaly and Follower quests.",
            tooltip_prefer_research_target = "Randomizer picks quests with Research Target when available.",
        },
        quest_ref = {
            name = "Quest Reference",
            tooltip_input_filter = "Quest Name Filter",
            header_name = "Quest Name",
            header_id = "Quest ID",
            header_map = "Map",
            header_level = "Level",
            tooltip_quest_no = "Click to set Quest ID.",
        },
    },
    actions = {
        button_post = "Post",
        button_randomize = "Randomize",
    },
    options = {
        box_auto_post = "Auto Post",
        box_auto_randomize = "Auto Randomize",
        box_auto_depart = "Auto Depart",
        box_send_join_request = "Send Join Request",
        box_filter_quest_reference = "Filter Quest Reference",
        box_bring_servant = "Bring Followers",
        tooltip_auto_post = "Automatically post a new quest when the active quest is completed.",
        tooltip_auto_randomize = "Automatically randomize the quest before posting.",
        tooltip_auto_depart = "Start quest immediately after posting.",
        tooltip_bring_servant = "Take followers with you when available.",
        tooltip_send_join_request = "Send Join Request when available.",
    },
    errors = {
        speedrun_online = "Speedrun Mode cannot be used in online lobbies.",
        invalid_quest_id = "Invalid Quest ID.",
        no_quests = "No quests remaining.",
    },
    mod = {
        input_quest_id = "Quest ID",
        combo_mode = "Mode",
        combo_mode_values = {
            QUEST_COUNTER = "Quest Counter",
            QUEST_BOARD = "Quest Board",
        },
        combo_quest = "Quest Type",
        combo_quest_values = {
            SPECIFIC = "Specific",
            RANDOM_LOW_RANK = "Random Low Rank",
            RANDOM_HIGH_RANK = "Random High Rank",
            RANDOM_MASTER_RANK = "Random Master Rank",
            RANDOM_MYSTERY = "Random Anomaly",
            RANDOM_RAMPAGE = "Random Rampage",
            RANDOM_RANDOM_MYSTERY = "Random Anomaly Investigation",
            RANDOM_SPECIAL_RANDOM_MYSTERY = "Random Special Investigation",
        },
        combo_target = "Target",
        combo_rampage_target = "Major Threats",
        combo_level = "Level",
        category_random_rampage = "Random Rampage",
        category_random_random_mystery = "Random Anomaly Investigation",
        combo_party_size = "Party Size",
        combo_party_size_values = {
            ["2"] = "Two Players Max",
            ["4"] = "Four Players Max",
        },
        combo_item = "Afflicted Materials",
        slider_level_max = "Lv Max",
        slider_level_min = "Lv Min",
        combo_servant = "Follower",
        combo_servant_weapon = "Weapon",
        category_servant = "Followers",
        category_quest_board = "Quest Board",
    },
}
